### ISSUE TITLE
Find and implement the best cryptography available

### ISSUE THREAD

**Issue by Kmaschta** [marmelab/comfygure#33]
# TODO
- [x] Use Initialization Vector (IV) in the encryption functions (#92)
- [x] Sign every encrypted data with HMAC and check it both server-side (optional) and client-side before usage (#93)
- [ ] Don't store the private key in plain text

### Reference / Docs
-> [AES 256 with an Initialization Vector](http://vancelucas.com/blog/stronger-encryption-and-decryption-in-node-js/)
-> [Check HMAC](http://www.levigross.com/2014/03/30/how-to-write-an-encrypt-and-decrypt-api-for-data-at-rest-in-nodejs/)
-> [Symmetric Cryptography (AES) with WebCrypto and Node.js](https://coolaj86.com/articles/symmetric-cryptography-aes-with-webcrypto-and-node-js/)

**Comment by Kmaschta** [comment]
-> [AES 256 with an Initialization Vector](http://vancelucas.com/blog/stronger-encryption-and-decryption-in-node-js/)

**Comment by Kmaschta** [comment]
The last point will be adressed by the issue #126
